
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Francisco A. Reyes
 */
public class GenClave extends javax.swing.JFrame {
    Random aleatorio = new Random();
    int numCaract;
    /**
     * Creates new form GenClave
     */
    public GenClave() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        seleccion = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaPass = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        nCaracteres = new javax.swing.JTextField();
        repetir = new javax.swing.JCheckBox();
        mayusculas = new javax.swing.JCheckBox();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        seleccion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alfabética", "Alfanumérica", "Numérica", "Completa" }));

        jButton1.setText("Generar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        areaPass.setColumns(20);
        areaPass.setRows(5);
        jScrollPane1.setViewportView(areaPass);

        jLabel1.setText("Nº caracteres del pass:");

        repetir.setText("Repetir Caracteres");

        mayusculas.setText("Todo Mayúsculas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(repetir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mayusculas))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(seleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nCaracteres, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 67, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1)
                    .addComponent(nCaracteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(repetir)
                    .addComponent(mayusculas))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        areaPass.setText(null);
        
        try {
        numCaract = Integer.valueOf(nCaracteres.getText());
        } catch (NumberFormatException e1){
            JOptionPane.showMessageDialog(this, "Error, introduce un número");
        }
        int seleccionado = seleccion.getSelectedIndex();
        String contraseña = "";
        String caracterPass = "";
        
        boolean repe = repetir.isSelected();
        boolean mayus = mayusculas.isSelected();
        
            for (int i = 0; i<numCaract; i++) {

                switch (seleccionado) {
                    case 0:
                        if (numCaract > 26 && repe == false) {
                            JOptionPane.showMessageDialog(this, "Error, contraseña demasiado larga");
                            i=numCaract+1;
                        } else {
                            int opcion1 = aleatorio.nextInt(26) + 'a';
                            caracterPass = ((char) opcion1 + "");
                        }
                        break;
                    case 1:
                        int nuevoAleatorio = aleatorio.nextInt(2);

                        if (numCaract > 36 && repe==false) {
                            JOptionPane.showMessageDialog(this, "Error, contraseña demasiado larga\nSelecciona botón Repetir Caracteres");
                            i=numCaract+1;
                        } else {  
                            if (nuevoAleatorio == 0){
                                int opcion2 = aleatorio.nextInt(10)+'0';
                                caracterPass = ((char) opcion2 + "");
                            } else {
                                int opcion2_2 = aleatorio.nextInt(26) + 'a';
                                caracterPass = ((char) opcion2_2 + "");
                            }
                        }    
                        break;
                    case 2:
                        if (numCaract > 10 && repe==false) {
                            JOptionPane.showMessageDialog(this, "Error, contraseña demasiado larga\nSelecciona botón Repetir Caracteres");
                            i=numCaract+1;
                        } else {
                            int opcion3 = aleatorio.nextInt('9'-'0'+1)+'0';
                            caracterPass = ((char) opcion3 + "");
                            
                        }
                    break;
                    case 3:
                        if (numCaract > 68 && mayus==true && repe==false) {
                            JOptionPane.showMessageDialog(this, "Error, contraseña demasiado larga\nSelecciona botón Repetir Caracteres");
                            i=numCaract+1;
                        } else {
                            if (numCaract > 94 && repe==false) {
                                JOptionPane.showMessageDialog(this, "Error, contraseña demasiado larga\nSelecciona botón Repetir Caracteres");
                                i=numCaract +1;
                            } else {
                            int opcion4 = aleatorio.nextInt('~' - '!' +1)+'!';
                            caracterPass = ((char)opcion4 + "");
                            
                            
                            }
                        }
                    break;
                    
                }
                if (contraseña.contains(caracterPass) && repe==false) {
                    i--;
                } else {
                    contraseña += caracterPass;
                }
                
                if (mayusculas.isSelected()) {
                    contraseña = contraseña.toUpperCase();
                }
            }
            
        areaPass.setText(contraseña);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenClave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenClave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenClave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenClave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenClave().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaPass;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox mayusculas;
    private javax.swing.JTextField nCaracteres;
    private javax.swing.JCheckBox repetir;
    private javax.swing.JComboBox seleccion;
    // End of variables declaration//GEN-END:variables
}
