
import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Francisco A. Reyes
 */
public class GenDias extends javax.swing.JFrame {
        Random nDia = new Random();
        
    /**
     * Creates new form GenDias
     */
    public GenDias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGenera = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areatxt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGenera.setText("Generar Días");
        btnGenera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneraActionPerformed(evt);
            }
        });

        areatxt.setColumns(20);
        areatxt.setRows(5);
        jScrollPane1.setViewportView(areatxt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenera, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGenera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGeneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneraActionPerformed
        //Estos comandos permiten que al pulsar el botón, se muestre una nueva lista.
        areatxt.setText(null);
        int nDia2 = 0;
        int nAnterior = 0;
        //El bucle realiza numeros aleatorios y los almacena en una variable
        //hasta que el valor almacenado sea menor que el nuevo Random.
        boolean terminar = false;
        do {
            nDia2 = nDia.nextInt(7)+1;
            
            if (nDia2 >= nAnterior) {
                switch (nDia2){
                    case 1:
                        areatxt.append("Lunes\n");
                        nAnterior = 1;
                        break;
                    case 2:
                        areatxt.append("Martes\n");
                        nAnterior = 2;
                        break; 
                    case 3:
                        areatxt.append("Miercoles\n");
                        nAnterior = 3;
                        break;
                    case 4:
                        areatxt.append("Jueves\n");
                        nAnterior = 4;
                        break;
                    case 5:
                        areatxt.append("Viernes\n");
                        nAnterior = 5;
                        break;
                    case 6:
                        areatxt.append("Sábado\n");
                        nAnterior = 6;
                        break;
                    case 7:
                        areatxt.append("Domingo\n");
                        nAnterior = 7;
                        break;
                    default:
                        areatxt.setText("Error");
                }
            } else {
                //Al ser el num almacenado (nAnterior) menor, escribe el texto asignado
                //a ese valor y para el bucle modificando el valor booleano (terminar)
                
                switch (nDia2){
                    case 1:
                        areatxt.append("Lunes\n");
                        terminar = true;
                        break;
                    case 2:
                        areatxt.append("Martes\n");
                        terminar = true;
                        break; 
                    case 3:
                        areatxt.append("Miercoles\n");
                        terminar = true;
                        break;
                    case 4:
                        areatxt.append("Jueves\n");
                        terminar = true;
                        break;
                    case 5:
                        areatxt.append("Viernes\n");
                        terminar = true;
                        break;
                    case 6:
                        areatxt.append("Sábado\n");
                        terminar = true;
                        break;
                    case 7:
                        areatxt.append("Domingo\n");
                        terminar = true;
                        break;                
                }
            }
        } while (terminar == false);
        
        
    }//GEN-LAST:event_btnGeneraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenDias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenDias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenDias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenDias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenDias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areatxt;
    private javax.swing.JButton btnGenera;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
